# Generated by Django 5.1 on 2024-08-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mapBan1', models.CharField(max_length=50)),
                ('mapBan2', models.CharField(max_length=50)),
                ('mapPick1', models.CharField(max_length=50)),
                ('mapPick2', models.CharField(max_length=50)),
                ('mapBan3', models.CharField(max_length=50)),
                ('mapBan4', models.CharField(max_length=50)),
                ('mapPick3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('acs', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('kd', models.IntegerField()),
                ('kast', models.IntegerField()),
                ('adr', models.IntegerField()),
                ('hsp', models.IntegerField()),
                ('fk', models.IntegerField()),
                ('fd', models.IntegerField()),
                ('fkfd', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.ManyToManyField(through='scraper.PlayerMatchConnection', to='scraper.match'),
        ),
        migrations.CreateModel(
            name='PlayerTeamConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='currentTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playersCurrentTeam', to='scraper.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='players', through='scraper.PlayerTeamConnection', to='scraper.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='map1Winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map1Winner', to='scraper.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='map2Winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map2Winner', to='scraper.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='map3Winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map3Winner', to='scraper.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchesAsTeam1', to='scraper.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchesAsTeam2', to='scraper.team'),
        ),
    ]
