# Generated by Django 5.1 on 2024-08-21 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_match_matchwinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchconnection',
            name='match',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='playermatchconnection',
            name='player',
        ),
        migrations.CreateModel(
            name='MatchBO3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mapBan1', models.CharField(max_length=50)),
                ('mapBan2', models.CharField(max_length=50)),
                ('mapPick1', models.CharField(max_length=50)),
                ('mapPick2', models.CharField(max_length=50)),
                ('mapBan3', models.CharField(max_length=50)),
                ('mapBan4', models.CharField(max_length=50)),
                ('mapPick3', models.CharField(max_length=50)),
                ('map1Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map1WinnerBO3', to='scraper.team')),
                ('map2Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map2WinnerBO3', to='scraper.team')),
                ('map3Winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map3WinnerBO3', to='scraper.team')),
                ('matchWinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchWinnerBO3', to='scraper.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchesAsTeam1BO3', to='scraper.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchesAsTeam2BO3', to='scraper.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchBO5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mapBan1', models.CharField(max_length=50)),
                ('mapBan2', models.CharField(max_length=50)),
                ('mapPick1', models.CharField(max_length=50)),
                ('mapPick2', models.CharField(max_length=50)),
                ('mapPick3', models.CharField(max_length=50)),
                ('mapPick4', models.CharField(max_length=50)),
                ('mapPick5', models.CharField(max_length=50)),
                ('map1Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map1WinnerBO5', to='scraper.team')),
                ('map2Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map2WinnerBO5', to='scraper.team')),
                ('map3Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map3WinnerBO5', to='scraper.team')),
                ('map4Winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map4WinnerBO5', to='scraper.team')),
                ('map5Winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map5WinnerBO5', to='scraper.team')),
                ('matchWinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchWinnerBO5', to='scraper.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchesAsTeam1BO5', to='scraper.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchesAsTeam2BO5', to='scraper.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchBO3Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('acs', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('kd', models.IntegerField()),
                ('kast', models.IntegerField()),
                ('adr', models.IntegerField()),
                ('hsp', models.IntegerField()),
                ('fk', models.IntegerField()),
                ('fd', models.IntegerField()),
                ('fkfd', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.matchbo3')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='matchesBO3',
            field=models.ManyToManyField(related_name='players', through='scraper.PlayerMatchBO3Connection', to='scraper.matchbo3'),
        ),
        migrations.CreateModel(
            name='PlayerMatchBO5Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('acs', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('kd', models.IntegerField()),
                ('kast', models.IntegerField()),
                ('adr', models.IntegerField()),
                ('hsp', models.IntegerField()),
                ('fk', models.IntegerField()),
                ('fd', models.IntegerField()),
                ('fkfd', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.matchbo5')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='matchesBO5',
            field=models.ManyToManyField(related_name='players', through='scraper.PlayerMatchBO5Connection', to='scraper.matchbo5'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='PlayerMatchConnection',
        ),
    ]
