# Generated by Django 5.1 on 2024-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_player_isinactive_player_issub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='isInactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='isSub',
            field=models.BooleanField(default=False),
        ),
    ]
