# Generated by Django 5.1 on 2024-08-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_matchbo3_team1map1roundswon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchbo3',
            name='map3Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map3WinnerBO3', to='scraper.team'),
        ),
        migrations.AlterField(
            model_name='matchbo3',
            name='team1Map3RoundsWon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchbo3',
            name='team2Map3RoundsWon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
