# Generated by Django 5.1 on 2024-09-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_alter_matchbo5_map4winner_alter_matchbo5_map5winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='fkfd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='fkfd',
            field=models.FloatField(),
        ),
    ]
