# Generated by Django 5.1 on 2024-09-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_alter_playermatchbo3connection_fkfd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='hsp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='kast',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='hsp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='kast',
            field=models.FloatField(),
        ),
    ]
