# Generated by Django 5.1.1 on 2024-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_alter_player_currentteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='kast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='kast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
