# Generated by Django 5.0.4 on 2024-08-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_match_matchwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchWinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchWinner', to='scraper.team'),
        ),
    ]
