# Generated by Django 5.1 on 2024-08-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_player_isigl'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isInactive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='isSub',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
