# Generated by Django 5.1 on 2024-08-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_player_isinactive_alter_player_issub'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchbo3',
            name='team1Map1RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo3',
            name='team1Map2RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo3',
            name='team1Map3RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo3',
            name='team2Map1RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo3',
            name='team2Map2RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo3',
            name='team2Map3RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team1Map1RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team1Map2RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team1Map3RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team1Map4RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team1Map5RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team2Map1RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team2Map2RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team2Map3RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team2Map4RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbo5',
            name='team2Map5RoundsWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
