# Generated by Django 5.1 on 2024-08-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_matchbo3_map3winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchbo5',
            name='map4Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map4WinnerBO5', to='scraper.team'),
        ),
        migrations.AlterField(
            model_name='matchbo5',
            name='map5Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map5WinnerBO5', to='scraper.team'),
        ),
        migrations.AlterField(
            model_name='matchbo5',
            name='team1Map4RoundsWon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchbo5',
            name='team1Map5RoundsWon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchbo5',
            name='team2Map4RoundsWon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchbo5',
            name='team2Map5RoundsWon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
