# Generated by Django 5.1 on 2024-09-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_alter_playermatchbo3connection_hsp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='fkfd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='hsp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo3connection',
            name='kast',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='fkfd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='hsp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playermatchbo5connection',
            name='kast',
            field=models.IntegerField(),
        ),
    ]
